CREATE TABLE IF NOT EXISTS Article(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    intro TEXT NOT NULL,
    text TEXT NOT NULL, 
    date DATETIME
);

CREATE TABLE IF NOT EXISTS users(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name text NOT NULL,
    email TEXT NOT NULL,
    pwd TEXT NOT NULL
);